# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='parts',
            field=models.ManyToManyField(to='parts.Part'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(help_text=b"The robot's name", max_length=20),
        ),
    ]
