# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20160405_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(help_text=b"The robot's name.", max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='parts',
            field=models.ManyToManyField(blank=True, help_text=b'The parts used by this robot.', to='parts.Part'),
        ),
    ]
