# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20160405_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='parts',
            field=models.ManyToManyField(blank=True, help_text=b'The parts used by this robot.', to='products.Product'),
        ),
    ]
