# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price'),
        ('robots', '0004_auto_20160407_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[(b'F', b'Functional'), (b'D', b'Damaged'), (b'N', b'Nonfunctional')], default=b'F', max_length=1)),
                ('product', models.ForeignKey(help_text=b'The product for this robot part.', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='robot',
            name='parts',
        ),
        migrations.AddField(
            model_name='robotpart',
            name='robot',
            field=models.ForeignKey(help_text=b'The robot this part belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='robot_parts', to='robots.Robot'),
        ),
    ]
