# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(help_text=b'The name of the part.', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='retailer',
            field=models.ForeignKey(help_text=b'The retailer that sells this part.', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts.Retailer'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(help_text=b'The name of the retailer.', max_length=50),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='website',
            field=models.URLField(help_text=b'The website for the retailer.'),
        ),
    ]
