# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20160405_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='retailer',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
