# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.DecimalField(decimal_places=2, help_text=b'The cost of shipping for this purchase.', max_digits=8)),
                ('discounts', models.DecimalField(decimal_places=2, help_text=b'The total sum of any discounts applied to this purchase.', max_digits=8)),
                ('products', models.ManyToManyField(help_text=b'The parts included in this purchase.', to='products.Product')),
            ],
        ),
    ]
