# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0002_auto_20160405_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(help_text=b'The part that this product is for.', on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
            ],
        ),
    ]
