# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'The name of the retailer.', max_length=50)),
                ('website', models.URLField(help_text=b'The website for the retailer.')),
            ],
        ),
    ]
