# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
    ]
